### ISSUE TITLE
FileNotFoundError: gdb9_trunc.parquet in QM9 Training Tutorial

### ISSUE THREAD

**Issue by erwallace** [Exscientia/physicsml#12]
Hello,
I am running through your QM9 training tutorial and getting an error. I can't see gdb9_trunc in molflux.datasets.list_datasets() either so not sure where this is meant to be stored.

> from molflux.datasets import load_dataset_from_store
> dataset = load_dataset_from_store("gdb9_trunc.parquet")

Gives the error:

> FileNotFoundError: Unable to find 'C:/Users/wallace5/antimanybody/physicsml\gdb9_trunc.parquet'

Cheers

**Comment by wardhaddadin1** [comment]
Hello! Thanks for reaching out! 

This is a truncated file for running the examples in the docs (in github actions). If you want to run the example locally, you can just use the full dataset like this: 

`from molflux.datasets import load_dataset
dataset = load_dataset_from_store("gdb9", "rdkit")`

There is more info about datasets here: https://exscientia.github.io/physicsml/pages/datasets/qm_datasets.html

I will update the docs to state this explicitly. 

Let us know if you have any other problems!

Best, 
Ward

**Comment by erwallace** [comment]
Thanks so much for the quick response!
