### ISSUE TITLE
Training MACE on SPICE, RuntimeError: Class values must be smaller than num_classes.

### ISSUE THREAD

**Issue by erwallace** [Exscientia/physicsml#14]
Hello,

I am running into some issue when trying to train a MACE model on a subset of SPICE. 

I have successfully trained with ani1x/nequips (as in your tutorial) and ani1x/mace (using `tests/data/mace_model/model_config.json`). 

However when I try to train spice_trunc/mace I am getting the error  "Class values must be smaller than num_classes". The only things i have changed in the config are num_elements and the y features (see below). 

> model_config.config.datamodule.num_elements = len(atomic_numbers_dict)
> model_config.config.datamodule.y_graph_scalars = dft_total_energy
> model_config.config.datamodule.y_node_vectors = dft_total_gradient
> model_config.config.y_features = [dft_total_energy, dft_total_gradient]

After looking into your code and trying a few different values I think the error is related to num_elements but I'm not exactly sure what's wrong.

> RuntimeError                              Traceback (most recent call last)
> Cell In[21], line 10
>       7 #print(nequip_config_)
>       9 model = load_model_from_dict(model_config)
> ---> 10 model.train(
>      11     train_data=split_featurised_dataset["train"]
>      12 )
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\molflux\modelzoo\model.py:189, in ModelBase.train(self, train_data, **kwargs)
>     186     # Safeguard against invalid kwargs
>     187     raise_on_unrecognised_parameters(self._train_multi_data, **kwargs)
> --> 189     return self._train_multi_data(train_data=train_datasets, **kwargs)
>     191 else:
>     192     if isinstance(train_data, dict):
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\molflux\modelzoo\models\lightning\model.py:160, in LightningModelBase._train_multi_data(***failed resolving arguments***)
>     158 self._compile()
>     159 trainer = pl.Trainer(**self.model_config.trainer.pass_to_trainer())
> --> 160 trainer.fit(self.module, datamodule=datamodule, ckpt_path=ckpt_path)
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\trainer\trainer.py:544, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
>     542 self.state.status = TrainerStatus.RUNNING
>     543 self.training = True
> --> 544 call._call_and_handle_interrupt(
>     545     self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
>     546 )
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\trainer\call.py:44, in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
>      42     if trainer.strategy.launcher is not None:
>      43         return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
> ---> 44     return trainer_fn(*args, **kwargs)
>      46 except _TunerExitException:
>      47     _call_teardown_hook(trainer)
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\trainer\trainer.py:580, in Trainer._fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
>     573 assert self.state.fn is not None
>     574 ckpt_path = self._checkpoint_connector._select_ckpt_path(
>     575     self.state.fn,
>     576     ckpt_path,
>     577     model_provided=True,
>     578     model_connected=self.lightning_module is not None,
>     579 )
> --> 580 self._run(model, ckpt_path=ckpt_path)
>     582 assert self.state.stopped
>     583 self.training = False
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\trainer\trainer.py:989, in Trainer._run(self, model, ckpt_path)
>     984 self._signal_connector.register_signal_handlers()
>     986 # ----------------------------
>     987 # RUN THE TRAINER
>     988 # ----------------------------
> --> 989 results = self._run_stage()
>     991 # ----------------------------
>     992 # POST-Training CLEAN UP
>     993 # ----------------------------
>     994 log.debug(f"{self.__class__.__name__}: trainer tearing down")
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\trainer\trainer.py:1035, in Trainer._run_stage(self)
>    1033         self._run_sanity_check()
>    1034     with torch.autograd.set_detect_anomaly(self._detect_anomaly):
> -> 1035         self.fit_loop.run()
>    1036     return None
>    1037 raise RuntimeError(f"Unexpected state {self.state}")
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\loops\fit_loop.py:202, in _FitLoop.run(self)
>     200 try:
>     201     self.on_advance_start()
> --> 202     self.advance()
>     203     self.on_advance_end()
>     204     self._restarting = False
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\loops\fit_loop.py:359, in _FitLoop.advance(self)
>     357 with self.trainer.profiler.profile("run_training_epoch"):
>     358     assert self._data_fetcher is not None
> --> 359     self.epoch_loop.run(self._data_fetcher)
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\loops\training_epoch_loop.py:136, in _TrainingEpochLoop.run(self, data_fetcher)
>     134 while not self.done:
>     135     try:
> --> 136         self.advance(data_fetcher)
>     137         self.on_advance_end(data_fetcher)
>     138         self._restarting = False
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\loops\training_epoch_loop.py:202, in _TrainingEpochLoop.advance(self, data_fetcher)
>     200 else:
>     201     dataloader_iter = None
> --> 202     batch, _, __ = next(data_fetcher)
>     203     # TODO: we should instead use the batch_idx returned by the fetcher, however, that will require saving the
>     204     # fetcher state so that the batch_idx is correct after restarting
>     205     batch_idx = self.batch_idx + 1
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\loops\fetchers.py:127, in _PrefetchDataFetcher.__next__(self)
>     124         self.done = not self.batches
>     125 elif not self.done:
>     126     # this will run only when no pre-fetching was done.
> --> 127     batch = super().__next__()
>     128 else:
>     129     # the iterator is empty
>     130     raise StopIteration
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\loops\fetchers.py:56, in _DataFetcher.__next__(self)
>      54 self._start_profiler()
>      55 try:
> ---> 56     batch = next(self.iterator)
>      57 except StopIteration:
>      58     self.done = True
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\utilities\combined_loader.py:326, in CombinedLoader.__next__(self)
>     324 def __next__(self) -> _ITERATOR_RETURN:
>     325     assert self._iterator is not None
> --> 326     out = next(self._iterator)
>     327     if isinstance(self._iterator, _Sequential):
>     328         return out
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\lightning\pytorch\utilities\combined_loader.py:74, in _MaxSizeCycle.__next__(self)
>      72 for i in range(n):
>      73     try:
> ---> 74         out[i] = next(self.iterators[i])
>      75     except StopIteration:
>      76         self._consumed[i] = True
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\torch\utils\data\dataloader.py:633, in _BaseDataLoaderIter.__next__(self)
>     630 if self._sampler_iter is None:
>     631     # TODO(https://github.com/pytorch/pytorch/issues/76750)
>     632     self._reset()  # type: ignore[call-arg]
> --> 633 data = self._next_data()
>     634 self._num_yielded += 1
>     635 if self._dataset_kind == _DatasetKind.Iterable and \
>     636         self._IterableDataset_len_called is not None and \
>     637         self._num_yielded > self._IterableDataset_len_called:
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\torch\utils\data\dataloader.py:677, in _SingleProcessDataLoaderIter._next_data(self)
>     675 def _next_data(self):
>     676     index = self._next_index()  # may raise StopIteration
> --> 677     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>     678     if self._pin_memory:
>     679         data = _utils.pin_memory.pin_memory(data, self._pin_memory_device)
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\torch\utils\data\_utils\fetch.py:51, in _MapDatasetFetcher.fetch(self, possibly_batched_index)
>      49         data = self.dataset.__getitems__(possibly_batched_index)
>      50     else:
> ---> 51         data = [self.dataset[idx] for idx in possibly_batched_index]
>      52 else:
>      53     data = self.dataset[possibly_batched_index]
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\torch\utils\data\_utils\fetch.py:51, in <listcomp>(.0)
>      49         data = self.dataset.__getitems__(possibly_batched_index)
>      50     else:
> ---> 51         data = [self.dataset[idx] for idx in possibly_batched_index]
>      52 else:
>      53     data = self.dataset[possibly_batched_index]
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\torch_geometric\data\dataset.py:263, in Dataset.__getitem__(self, idx)
>     253 r"""In case :obj:`idx` is of type integer, will return the data object
>     254 at index :obj:`idx` (and transforms it in case :obj:`transform` is
>     255 present).
>     256 In case :obj:`idx` is a slicing object, *e.g.*, :obj:`[2:5]`, a list, a
>     257 tuple, or a :obj:`torch.Tensor` or :obj:`np.ndarray` of type long or
>     258 bool, will return a subset of the dataset at the specified indices."""
>     259 if (isinstance(idx, (int, np.integer))
>     260         or (isinstance(idx, Tensor) and idx.dim() == 0)
>     261         or (isinstance(idx, np.ndarray) and np.isscalar(idx))):
> --> 263     data = self.get(self.indices()[idx])
>     264     data = data if self.transform is None else self.transform(data)
>     265     return data
> 
> File ~\AppData\Local\miniforge3\envs\antimanybody\Lib\site-packages\physicsml\lightning\graph_datasets\graph_dataset.py:258, in GraphDataset.get(self, idx)
>     255 if raw_atomic_numbers is not None:
>     256     raw_atomic_numbers = torch.tensor(raw_atomic_numbers)
>     257     atomic_numbers: Optional[torch.Tensor] = (
> --> 258         torch.nn.functional.one_hot(
>     259             raw_atomic_numbers,
>     260             num_classes=self.num_elements,
>     261         )
>     262         * 1.0
>     263     )
>     264 else:
>     265     atomic_numbers = None
> 
> RuntimeError: Class values must be smaller than num_classes.

I am happy to email you a copy of the notebook if you have any questions.
Any help would be greatly appreciated.

Thanks,
Ewan

**Comment by erwallace** [comment]
Solved: needed to change model_config.num_node_feat = len(atomic_numbers_dict)

**Comment by wardhaddadin1** [comment]
Hello, glad it worked!

In general though, the num_node_feats is no necessarily equal only to the num of atomic numbers. It can also be larger if you use additional atom features like degree, formal charge, etc... 

Best, 
Ward

**Comment by erwallace** [comment]
Cheers Ward, that's useful to know.
