### ISSUE TITLE
Creating a conda environment with OpenMM-ML and PhysicsML

### ISSUE THREAD

**Issue by wardhaddadin1** [Exscientia/physicsml#34]
There have been some difficulties with installing `physicsml` in the same environment with openmm-ml. As a workaround, we have found that the following sequence of installs works

```
conda create -p ./.venv python=3.11
conda activate ./.venv
pip install physicsml
conda install openmm-ml pytorch-gpu -c conda-forge
```

@peastman can you try this an confirm if it works for you? Thanks!

**Comment by peastman** [comment]
Doing it that way works.  Here is what I did.

```
conda create --name test -c conda-forge python=3.11
conda activate test
pip install physicsml
mamba install -c conda-forge openmm-ml pytorch-gpu rdkit pytest
```

I then used `pytest tests/openmm` to run all the tests for the OpenMM interface, and everything passed.

Do you expect it to only work with Python 3.11, or should it also work with other versions?

**Comment by wardhaddadin1** [comment]
Ah that's great! 

It's compatible with 3.8, 3.9, 3.10, and 3.11 (tests run for all these versions)

**Comment by peastman** [comment]
What about supporting 3.12?

**Comment by wardhaddadin1** [comment]
We don't have plans to support it currently, but I think we will at some point.
