### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by peastman** [Exscientia/physicsml#35]
I have some models I trained with version 0.2.  I recently tried to upgrade to 0.3.  When I did, I found my models could still be loaded, but they produced completely different outputs.  Do you have any idea what could have caused it?

**Comment by wardhaddadin1** [comment]
Hello!

That's strange, the only change in `0.3.0` is adding the option to pass graph level features to the models (which are disabled by default). 

We have backward compatibility tests ([here](https://github.com/Exscientia/physicsml/blob/main/tests/openmm/test_openmm_nnp_potential.py)) and they are passing. 

Could you give a minimal failing example? 

Thanks, 
Ward

**Comment by peastman** [comment]
I just emailed an example to you.

**Comment by peastman** [comment]
I've also found that 0.3 is significantly slower than 0.2.  For example, one of my benchmarks decreased from 9.24 to 8.77 ns/day.

**Comment by peastman** [comment]
Upgrading to 0.3.1 has also fixed the performance decrease.  It may have been caused by the extra work to unnecessarily apply periodic boundary conditions.  It's now significantly faster than 0.2.  Have there been other changes that are expected to speed it up?
